# Generated by Django 4.2.5 on 2024-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
