# Generated by Django 4.2.5 on 2024-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
